Correct indentation of jxabuild script
Nova 1.2 has an awkward relationship to its nominal EditorConfig support, it seems.

diff --git a/JXA.novaextension/Scripts/bin/jxabuild b/JXA.novaextension/Scripts/bin/jxabuild
--- a/JXA.novaextension/Scripts/bin/jxabuild
+++ b/JXA.novaextension/Scripts/bin/jxabuild
@@ -14,8 +14,8 @@ abort_prefix="Aborting:"
 
 # Catch tasks started out of non-document tabs.
 if [[ -z "$1" ]]; then
-	echo "$abort_prefix no script file to build from." >&2
-	exit 1
+  echo "$abort_prefix no script file to build from." >&2
+  exit 1
 fi
 
 # Catch missing target information.
@@ -29,20 +29,20 @@ fi
 
 # Create the build directory if needed.
 if [[ ! -e "$JXABUILD_DIR" ]]; then
-	mkdir -p "$JXABUILD_DIR"
-	if (($? > 0)); then
-		echo "$abort_prefix could not create build directory '$JXABUILD_DIR'." >&2
-		exit 1
-	fi
+  mkdir -p "$JXABUILD_DIR"
+  if (($? > 0)); then
+    echo "$abort_prefix could not create build directory '$JXABUILD_DIR'." >&2
+    exit 1
+  fi
 fi
 
 # Ensure we have access to the build directory.
 if [[ ! -d "$JXABUILD_DIR" ]]; then
-	echo "$abort_prefix build directory '$JXABUILD_DIR' not available." >&2
-	exit 1
+  echo "$abort_prefix build directory '$JXABUILD_DIR' not available." >&2
+  exit 1
 elif [[ ! -w "$JXABUILD_DIR" ]]; then
-	echo "$abort_prefix build directory '$JXABUILD_DIR' not writable." >&2
-	exit 1
+  echo "$abort_prefix build directory '$JXABUILD_DIR' not writable." >&2
+  exit 1
 fi
 
 # Construct the command line.
